/* STARHOUND 0.9 // CEREBRO DE FRONTERA
   Tutorial contextual, hangar de naves, salidas cortas y capa de UX defensiva. */
(() => {
"use strict";
const V09 = { tutorialStep: 0, minimized: false, sortieBusy: false };
const TUTORIAL = [
 {title:"BIENVENIDO AL NIDO", text:"Soy CLIP-9, asistente de operaciones del Fleet Carrier. No necesitás memorizar esta máquina. Voy a guiarte desde el panel hasta tu primera recompensa.", target:"mapa", action:"ENTENDIDO"},
 {title:"01 // IDENTIDAD", text:"Primero necesitás una licencia operativa. Abrí IDENTIDAD en la columna izquierda. Podés inspeccionar cada cazador sin confirmar nada.", target:"cazador", action:"ABRIR IDENTIDAD"},
 {title:"02 // ELEGÍ TU CAZADOR", text:"Revisá especialidad, pasiva y desventaja. Asigná una identidad. Después volveré a aparecer.", target:"cazador", action:"IR AL DOSSIER"},
 {title:"03 // CONTRATO DE INICIACIÓN", text:"La Academia preparó una operación local. No hay salto interestelar: todo ocurre en el sistema actual. Abrí CONTRATOS y aceptá el primer trabajo disponible.", target:"contratos", action:"ABRIR CONTRATOS"},
 {title:"04 // EL PANEL NO ES EL MUNDO", text:"La carta táctica es tu vista general. La columna izquierda abre herramientas; la barra superior muestra recursos. FUEL mueve naves. HULL mide integridad. CR paga reparaciones y módulos.", target:"mapa", action:"VER CARTA"},
 {title:"05 // SUPERFICIE", text:"Cuando un caso está activo, SUPERFICIE baja al distrito actual. Entrá a lugares, observá y hablá con gente. Un minijuego sólo aparece si la acción del mundo lo justifica.", target:"explorar", action:"BAJAR A SUPERFICIE"},
 {title:"06 // HECHOS, NO PORCENTAJES", text:"Una fuente puede revelar una nave, implante, especie o afiliación. El ARCHIVO guarda el hecho y su procedencia. DEDUCCIÓN sirve para cruzarlo; STARHOUND no debería pensar por vos.", target:"archivo", action:"ABRIR ARCHIVO"},
 {title:"LICENCIA LIBERADA", text:"Tutorial operativo completado. Desde ahora la frontera no te marca un camino correcto. Aceptá contratos, mejorá el Fleet Carrier, comprá naves y administrá el riesgo. El mundo es tuyo.", target:"mapa", action:"EL MUNDO ES MÍO"}
];
const NAVES = [
 {id:"mule", nombre:"MULE-7", clase:"LANZADERA", rango:4, tanque:100, casco:100, bodega:8, costo:0, desc:"Fea, lenta y reparable con piezas de ascensor."},
 {id:"needle", nombre:"NEEDLE K2", clase:"INTERCEPTORA", rango:7, tanque:72, casco:74, bodega:3, costo:1800, desc:"Salta corto y huye rápido. Mala para traer media chatarrería."},
 {id:"nomad", nombre:"NOMAD 44", clase:"EXPLORADORA", rango:11, tanque:145, casco:88, bodega:12, costo:4200, desc:"Sensores de frontera y autonomía para rutas sin estaciones."},
 {id:"vulture", nombre:"VULTURE IX", clase:"CAZADORA", rango:8, tanque:92, casco:132, bodega:5, costo:6800, desc:"Blindaje frontal y firma térmica imposible de ignorar."}
];
const EVENTOS = [
 {t:"BALIZA MUERTA", d:"Una baliza minera emite tres pulsos y se apaga.", a:["ACOPLAR", "ESCANEAR", "IGNORAR"]},
 {t:"CONTACTO PIRATA", d:"Dos firmas cortan tu vector. Todavía no fijaron armas.", a:["FORZAR PASO", "APAGAR FIRMA", "NEGOCIAR"]},
 {t:"NUBE DE RESTOS", d:"Chatarra orbital. Puede haber celdas de combustible intactas.", a:["RECOLECTAR", "DRON", "SEGUIR"]},
 {t:"TRANSPONDEDOR CIVIL", d:"Una nave pide asistencia. La matrícula no coincide con el casco.", a:["RESPONDER", "OBSERVAR", "CORTAR ENLACE"]},
 {t:"TORMENTA IÓNICA", d:"Los sensores pierden profundidad y el reactor empieza a oscilar.", a:["ATRAVESAR", "DERIVAR", "ANCLAR"]}
];
function perfil(){ const p=typeof shPerfilMundo==="function"?shPerfilMundo():STARHOUND.perfil; p.v09 ||= {}; p.v09.tutorial ||= {done:false, step:0, skipped:false}; p.v09.hangar ||= {owned:["mule"], active:"mule", upgrades:{}}; p.v09.sorties ||= 0; return p; }
function save(){ try{ if(typeof shGuardar==="function") shGuardar(); else ALMACEN_STARHOUND.guardar(); }catch(e){console.warn(e)} }
function screen(){ return document.querySelector(".pantalla-starhound"); }
function go(x){ if(typeof shIr==="function") shIr(x); }
function esc(s){ return String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c])); }

function mountClip(){
 if(document.getElementById("sh-clip")) return;
 const el=document.createElement("aside"); el.id="sh-clip"; el.className="sh-clip hidden"; el.innerHTML=`<div class="sh-clip-head"><span class="sh-clip-face">C9</span><div><b>CLIP-9</b><small>ASISTENTE DE OPERACIONES</small></div><button data-clip-min title="Minimizar">_</button><button data-clip-close title="Omitir tutorial">×</button></div><div class="sh-clip-body"><small id="sh-clip-step"></small><h2 id="sh-clip-title"></h2><p id="sh-clip-text"></p><button id="sh-clip-action"></button></div>`; document.body.appendChild(el);
 el.querySelector("[data-clip-min]").onclick=()=>{V09.minimized=!V09.minimized;el.classList.toggle("minimized",V09.minimized)};
 el.querySelector("[data-clip-close]").onclick=()=>{ if(confirm("¿Omitir la guía de inicio? Podés reactivarla desde PERFIL / SAVE.")){const p=perfil();p.v09.tutorial.done=true;p.v09.tutorial.skipped=true;save();el.classList.add("hidden");}};
}
function showTutorial(){ const p=perfil(); mountClip(); const el=document.getElementById("sh-clip"); if(p.v09.tutorial.done){el.classList.add("hidden");return;} V09.tutorialStep=Math.min(p.v09.tutorial.step||0,TUTORIAL.length-1); const s=TUTORIAL[V09.tutorialStep]; el.classList.remove("hidden"); el.classList.remove("minimized"); V09.minimized=false; document.getElementById("sh-clip-step").textContent=`GUÍA ${V09.tutorialStep+1}/${TUTORIAL.length}`; document.getElementById("sh-clip-title").textContent=s.title; document.getElementById("sh-clip-text").textContent=s.text; const b=document.getElementById("sh-clip-action"); b.textContent=s.action; b.onclick=()=>{go(s.target); advanceTutorial();}; }
function advanceTutorial(){ const p=perfil(); if(V09.tutorialStep>=TUTORIAL.length-1){p.v09.tutorial.done=true;p.v09.tutorial.step=TUTORIAL.length;save();document.getElementById("sh-clip")?.classList.add("hidden");go("mapa");if(typeof notificar==="function")notificar("LICENCIA LIBERADA // EL MUNDO ES TUYO");return;} p.v09.tutorial.step=++V09.tutorialStep; save(); setTimeout(showTutorial,120); }
function resetTutorial(){const p=perfil();p.v09.tutorial={done:false,step:0,skipped:false};save();showTutorial();}

function renderHangar(){ const p=perfil(), h=p.v09.hangar, active=NAVES.find(n=>n.id===h.active)||NAVES[0]; screen().innerHTML=`<section class="v09-page"><header class="v09-page-head"><button data-v09-back>← CARTA</button><div><small>FLEET CARRIER // CUBIERTA DE VUELO</small><h1>HANGAR DE LANZADERAS</h1><p>El Carrier es tu base. Estas son las naves que realmente abandonan el hangar.</p></div></header><div class="v09-hangar"><aside>${NAVES.map(n=>`<button data-ship="${n.id}" class="${n.id===active.id?'active':''} ${h.owned.includes(n.id)?'owned':''}"><span>${h.owned.includes(n.id)?'EN HANGAR':'CATÁLOGO'}</span><b>${esc(n.nombre)}</b><small>${esc(n.clase)}</small></button>`).join('')}</aside><main><div class="v09-ship-mark">${active.clase.slice(0,2)}</div><small>NAVE ACTIVA // ${esc(active.clase)}</small><h2>${esc(active.nombre)}</h2><p>${esc(active.desc)}</p><div class="v09-specs"><span>RANGO<b>${active.rango} LY</b></span><span>TANQUE<b>${active.tanque}</b></span><span>CASCO<b>${active.casco}</b></span><span>BODEGA<b>${active.bodega}</b></span></div><div class="v09-actions">${h.owned.includes(active.id)?`<button id="v09-use" ${h.active===active.id?'disabled':''}>${h.active===active.id?'NAVE ACTIVA':'ASIGNAR NAVE'}</button>`:`<button id="v09-buy" ${p.creditos<active.costo?'disabled':''}>COMPRAR // ${active.costo} CR</button>`}<button id="v09-sortie">SALIDA CORTA // BUSCAR RECURSOS</button></div></main></div></section>`;
 document.querySelector('[data-v09-back]').onclick=()=>go('mapa'); document.querySelectorAll('[data-ship]').forEach(b=>b.onclick=()=>{h.preview=b.dataset.ship; const n=NAVES.find(x=>x.id===b.dataset.ship); h.activePreview=n.id; renderHangarPreview(n);}); bindHangar(active);
}
function renderHangarPreview(n){const p=perfil();p.v09.hangar._view=n.id; const h=p.v09.hangar; screen().querySelector('.v09-hangar main').innerHTML=`<div class="v09-ship-mark">${n.clase.slice(0,2)}</div><small>${h.owned.includes(n.id)?'EN HANGAR':'CATÁLOGO'} // ${esc(n.clase)}</small><h2>${esc(n.nombre)}</h2><p>${esc(n.desc)}</p><div class="v09-specs"><span>RANGO<b>${n.rango} LY</b></span><span>TANQUE<b>${n.tanque}</b></span><span>CASCO<b>${n.casco}</b></span><span>BODEGA<b>${n.bodega}</b></span></div><div class="v09-actions">${h.owned.includes(n.id)?`<button id="v09-use" ${h.active===n.id?'disabled':''}>${h.active===n.id?'NAVE ACTIVA':'ASIGNAR NAVE'}</button>`:`<button id="v09-buy" ${p.creditos<n.costo?'disabled':''}>COMPRAR // ${n.costo} CR</button>`}<button id="v09-sortie">SALIDA CORTA // BUSCAR RECURSOS</button></div>`; bindHangar(n);}
function bindHangar(n){const p=perfil(),h=p.v09.hangar; const use=document.getElementById('v09-use'),buy=document.getElementById('v09-buy'),sortie=document.getElementById('v09-sortie'); if(use)use.onclick=()=>{h.active=n.id;save();renderHangar();}; if(buy)buy.onclick=()=>{if(p.creditos<n.costo)return;p.creditos-=n.costo;h.owned.push(n.id);h.active=n.id;save();renderHangar();}; if(sortie)sortie.onclick=()=>startSortie(n);}
function startSortie(n){if(V09.sortieBusy)return;V09.sortieBusy=true; const p=perfil(),ev=EVENTOS[Math.floor(Math.random()*EVENTOS.length)]; screen().innerHTML=`<section class="v09-sortie"><header><small>SALIDA ${String((p.v09.sorties||0)+1).padStart(3,'0')} // ${esc(n.nombre)}</small><h1>${esc(ev.t)}</h1></header><div class="v09-radar"><i></i><b>?</b></div><p>${esc(ev.d)}</p><div class="v09-choice">${ev.a.map((a,i)=>`<button data-ev="${i}">${esc(a)}</button>`).join('')}</div></section>`; document.querySelectorAll('[data-ev]').forEach(b=>b.onclick=()=>resolveSortie(+b.dataset.ev,ev,n));}
function resolveSortie(choice,ev,n){const p=perfil();p.v09.sorties=(p.v09.sorties||0)+1; const roll=(Math.random()+choice*.13+n.rango*.015); let title,text; if(roll>.78){const fuel=12+Math.floor(Math.random()*20);p.nave.combustible=Math.min(100,(p.nave.combustible||0)+fuel);title='RECURSO RECUPERADO';text=`La salida rinde ${fuel} unidades de combustible. La frontera, por una vez, paga.`;}else if(roll>.35){const cr=70+Math.floor(Math.random()*180);p.creditos+=cr;title='CONTACTO RESUELTO';text=`Volvés con ${cr} CR y una historia que probablemente exageres.`;}else{const dmg=5+Math.floor(Math.random()*13);p.nave.casco=Math.max(1,(p.nave.casco||100)-dmg);title='REGRESO FORZOSO';text=`Perdés ${dmg}% de casco. No todo punto brillante es botín.`;}save();V09.sortieBusy=false;screen().innerHTML=`<section class="v09-result"><small>${esc(ev.t)} // INFORME DE SALIDA</small><h1>${title}</h1><p>${text}</p><button id="v09-return-hangar">VOLVER AL HANGAR</button></section>`;document.getElementById('v09-return-hangar').onclick=renderHangar; if(typeof shActualizarBarraEstrategica==='function')shActualizarBarraEstrategica();}

function patchNav(){ const nav=document.querySelector('.navegacion-starhound'); if(!nav||nav.querySelector('[data-sh="hangar"]'))return; const base=nav.querySelector('[data-sh="base"]'); if(base)base.insertAdjacentHTML('afterend','<button data-sh="hangar"><i>△</i><span>HANGAR / NAVES</span></button>'); nav.querySelector('[data-sh="hangar"]').onclick=()=>{document.querySelectorAll('[data-sh]').forEach(b=>b.classList.toggle('activo',b.dataset.sh==='hangar'));renderHangar();}; }
function patchProfile(){ const original=window.renderPerfil; if(typeof original!=="function")return; window.renderPerfil=function(){original(); const host=screen(); const box=document.createElement('section');box.className='v09-profile-tools';box.innerHTML='<small>ASISTENCIA DE OPERACIONES</small><h2>GUÍA CLIP-9</h2><p>Reinicia el recorrido interactivo de la terminal sin borrar tu progreso.</p><button id="v09-reset-tutorial">REINICIAR TUTORIAL</button>';host.appendChild(box);document.getElementById('v09-reset-tutorial').onclick=resetTutorial;}; }
function boot(){ STARHOUND.version='0.9.0'; perfil(); mountClip(); patchNav(); patchProfile(); /* CLIP flotante desactivado: usa Spotlight 1.0 */ }
window.addEventListener('load',()=>setTimeout(boot,120));
window.STARHOUND_V09={showTutorial,resetTutorial,renderHangar,startSortie};
})();
